name: cml_workflow

on: [pull_request]

jobs:
  run:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - uses: iterative/setup-cml@v1

      - uses: iterative/setup-dvc@v1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: cml
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_API_PW: ${{ secrets.GOOGLE_API_PW }}
          CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$GOOGLE_API_PW" \
          --output credentials.json credentials.json.gpg
          
          pip install -r requirements.txt
          
          # Pull dataset with DVC
          echo "Pulling data from DVC"
          dvc pull

          # Reproduce pipeline
          echo "Reproducing pipeline"
          dvc repro

          # Use DVC metrics diff to compare metrics to master
          git fetch --prune --unshallow
          dvc metrics diff --show-md main > report.md

          # Add confusion matrix figure to report
          echo '![](./confusion_matrix.png)' >> report.md

          # Add loss figure to report
          dvc plots diff --target loss.csv --show-vega main > vega.json
          vl2png vega.json -s 1.3 > vega.png
          echo '![](./vega.png)' >> report.md
          cml comment create report.md
          
          # Push model on PR
          cml ci
          git add model/
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
